name: xsarsea-tests
channels:
  - conda-forge
dependencies:
  - ipython
  - pre-commit
  - pytest
  - pytest-reportlog
  - pytest-cov
  - numpy
  - toolz
  - cytoolz
  - python-dateutil
  - construct
  - xarray
  - pandas
  - aiohttp
  - fsspec
  - dask
  - numba
  - opencv
  - pyyaml
  - matplotlib
  - h5netcdf
  - scipy
